# Generated by Django 4.2 on 2025-02-10 19:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceBooklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mileage', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=500)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(5.0, message='Cost must be at least 5.00 PLN')])),
            ],
            options={
                'verbose_name': 'booklet',
                'verbose_name_plural': 'booklets',
                'db_table': 'booklets',
                'ordering': ['-date', '-mileage'],
            },
        ),
    ]
