# Generated by Django 4.2 on 2025-02-10 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        ('service_booklets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicebooklet',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booklets', to='vehicles.vehicle'),
        ),
    ]
